name: '@zju-health-report/action Demo'

on:
  workflow_dispatch:
  schedule:
    # `0 23 * * *` 表示UTC 23:00，即北京时间7:00打卡（经测试，实际运行时间比设定时间晚几分钟到几十分钟）。
    - cron: '0 23 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - username: ZJU_USERNAME2 #hemubin
            password: ZJU_PASSWORD2
            dingtalk_token: DINGTALK_TOKEN2
          #- username: ZJU_USERNAME #fanxiaoxiao
            #password: ZJU_PASSWORD
            #dingtalk_token: DINGTALK_TOKEN
          #- username: ZJU_USERNAME3 #jiangjiazhi
            #password: ZJU_PASSWORD3
            #dingtalk_token: DINGTALK_TOKEN3
          - username: ZJU_USERNAME4 #pengshiyi
            password: ZJU_PASSWORD4
            dingtalk_token: DINGTALK_TOKEN4
          - username: ZJU_USERNAME5 #hezijun
            password: ZJU_PASSWORD5
            dingtalk_token: DINGTALK_TOKEN5
          - username: ZJU_USERNAME6 #zhangyuhuang
            password: ZJU_PASSWORD6
            dingtalk_token: DINGTALK_TOKEN6
          - username: ZJU_USERNAME7 #gengweihang
            password: ZJU_PASSWORD7
            dingtalk_token: DINGTALK_TOKEN7
          - username: ZJU_USERNAME8 #nihuwei
            password: ZJU_PASSWORD8
            dingtalk_token: DINGTALK_TOKEN8
          - username: ZJU_USERNAME9 #liyifei
            password: ZJU_PASSWORD9
            dingtalk_token: DINGTALK_TOKEN9
    steps:
      - name: 打卡
        uses: zju-health-report/action@release
        with:
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          dingtalk_token: ${{ secrets[matrix.dingtalk_token] }}
        env:
          ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
